### ISSUE TITLE
Directional Linking is impossible in the move's comment

### ISSUE THREAD

**Issue by Ilan2271** [chrislicodes/obsidian-chess-study#6]
Hi, I'd like to build my own chess database with a repertory of openings, but I can't link a move to a new not in the text space.
It would be really helpful to explore variations.

Hope you could do something.
Have a great day, and thanks for your amazing plugin.

**Comment by chrislicodes** [comment]
Hey! I am not sure I understand - can you explain this in different words again please? You want to be able to add links in the comment section?

**Comment by latenitecoding** [comment]
> Hi, I'd like to build my own chess database with a repertory of openings, but I can't link a move to a new not in the text space. It would be really helpful to explore variations.
> 
> Hope you could do something. Have a great day, and thanks for your amazing plugin.

If I understand this request correctly, @Ilan2271 is asking for markdown linking within the comment section of the board. If that's correct, I'm not sure that this feature should be pursued. It maybe possible to accomplish, but it would require that the plugin parse the comments as markdown. In order to have file linking, users would also need to provide the relative path to the file and maintain that file path over time. Or at least the file ID that obsidian uses.

I think this kind of feature is just already done best by Obsidian. Users can turn off the comments on the board and write the comments below the board with full Obsidian support.

**Comment by chrislicodes** [comment]
I agree with @latenitecoding and will close this issue.
